Motd: '&5Flame&bKits &6Venha Treinar Seu PvP'
StatusMotd: '&6Novidades: &aNovos Kits: Ninja e Reverse'
NomeServer: '&aFlame&eKits'
MensagemAutomatica1: '&bServidor em beta'
MensagemAutomatica2: '&eDivulgue O Nosso Servidor'
MensagemAutomatica3: '&aEm Breve Kits Secundarios'
MensagemAutomatica4: '&dTwitter @FlameKits'
MensagemAutomatica5: '&c'
MensagemAplicar1: '&bAplique-se no link: sem formulario por enquanto'
MensagemYoutuber1: '&bPara se tornar YT No Servidor Necessita-se de 250 Subs + Video No Servidor'
MensagemYoutuber2: '&cEssa TAG Não é Liberada'
MensagemYoutuber3: '&cEssa TAG Não é Liberada'
